package com.cs414j.monopoly.view;

import java.awt.TextField;
import java.util.LinkedList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JTextField;
import com.cs414j.monopoly.controller.MonopolyMain;
import com.cs414j.monopoly.controller.MonopolyOptions;
import com.cs414j.monopoly.model.Player;



/**
 *
 * @author maalv
 */
public class AuctionPanel extends javax.swing.JPanel {
	
	Player player;
	public static List<Player> tempPlayer = new LinkedList<>();

    public AuctionPanel(Player currentPlayer) {
    	this.player = currentPlayer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	playerNames = new JLabel[3];
    	bidPrice = new JTextField[3];
        topicLabel = new javax.swing.JLabel();


        for(int i=0;i<playerNames.length; i++) {
        	playerNames[i] = new javax.swing.JLabel();
        	bidPrice[i] = new javax.swing.JTextField();
        	playerNames[i].setEnabled(false);
        	bidPrice[i].hide();
        }
        for(Player p: MonopolyMain.players) {
        	if(p!=player) {
        		tempPlayer.add(p);
        	}
        }
        for(int i=0;i<tempPlayer.size();i++) {
        	playerNames[i].setText(tempPlayer.get(i).getName());
        	playerNames[i].setEnabled(true);
        	bidPrice[i].show();
        }        


        topicLabel.setText("Enter Auction Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerNames[2])
                    .addComponent(playerNames[1])
                    .addComponent(playerNames[0]))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bidPrice[1], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(bidPrice[0], javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bidPrice[2], javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(topicLabel)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(topicLabel)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNames[0])
                    .addComponent(bidPrice[0], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNames[1])
                    .addComponent(bidPrice[1], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNames[2])
                    .addComponent(bidPrice[2], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
    }// </editor-fold>                                                               


    public static javax.swing.JLabel[] playerNames;
    private javax.swing.JLabel topicLabel;
    public static javax.swing.JTextField[] bidPrice;
    // End of variables declaration                      
}

