/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cs414j.monopoly.view;

/**
 *
 * @author maalv
 */
public class AuctionPanel extends javax.swing.JPanel {
	
	int bidValuePlace;

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form RemoteAuction
     */
    public AuctionPanel(String propertyName) {
        initComponents(propertyName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String propertyName) {

        auctionLabel = new javax.swing.JLabel();
        bidLabel = new javax.swing.JLabel();
        bidValue = new javax.swing.JTextField();
        bidLabel.setText("Enter your bid");
        setAuctionLabel(propertyName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(bidLabel)
                        .addGap(76, 76, 76)
                        .addComponent(bidValue, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(auctionLabel)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(auctionLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bidLabel)
                    .addComponent(bidValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

                                   


    public void setAuctionLabel(String propertyName) {
    	auctionLabel.setText("Auction for Property: "+propertyName);
	}
    
    public int getBidValue() {
    	return bidValuePlace; 
    }
    
    public void setBidValue() {
    	bidValuePlace = Integer.parseInt(bidValue.getText());
    }


	// Variables declaration - do not modify                     
    private javax.swing.JLabel auctionLabel;
    private javax.swing.JLabel bidLabel;
    private javax.swing.JTextField bidValue;
                
}
