package com.cs414j.monopoly.client.view;

import javax.swing.JPanel;

public class FixedDieValuePanel extends JPanel{

	int leftDieValue,rightDieValue;
	

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form PlayerInfoTable
     */
    public FixedDieValuePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        dieLabel = new javax.swing.JLabel();
        leftDieLabel = new javax.swing.JLabel();
        rightDieLabel = new javax.swing.JLabel();
        leftDieValueText = new javax.swing.JTextField();
        rightDieValueText = new javax.swing.JTextField();

        dieLabel.setText("Enter Dice Value(1-6)");

        leftDieLabel.setText("Left Die");

        rightDieLabel.setText("Right Die");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rightDieLabel)
                    .addComponent(leftDieLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(leftDieValueText, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(rightDieValueText))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(dieLabel)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(dieLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftDieLabel)
                    .addComponent(leftDieValueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightDieLabel)
                    .addComponent(rightDieValueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    

    public int getLeftDieValue() {
		return leftDieValue;
	}


	public int getRightDieValue() {
		return rightDieValue;
	}

	public void setDiceValue() {
		leftDieValue = Integer.parseInt(leftDieValueText.getText());
		rightDieValue = Integer.parseInt(rightDieValueText.getText());
	}



	// Variables declaration - do not modify                     
    private javax.swing.JLabel dieLabel;
    private javax.swing.JLabel leftDieLabel;
    private javax.swing.JLabel rightDieLabel;
    private javax.swing.JTextField leftDieValueText;
    private javax.swing.JTextField rightDieValueText;
    // End of variables declaration                   
}

